export const themes = {
    light: {
        primary: '#4F46E5',
        primaryOpacity: '#EEF2FF',
        onPrimary: '#FFFFFF',
        secondary: '#46b5e5',
        tertiary: '#E0E7FF',
        background: '#F9FAFB',
        onBackground: '#4B5663',
        surface: '#FFFFFF',
        surfaceSecondary: '#F3F4F6',
        text: '#111727',
        textSecondary: '#7C828E',
        outline: '#DBDAD8',
        green: '#DFF6E0',
        onGreen: '#1D7B2E',
        blue: '#DBE9FE',
        onBlue: '#1D40B0',
        yellow: '#FEF9C3',
        onYellow: '#916025',
        orange: '#FEE7DB',
        onOrange: '#B0581D'
    },
    dark: {
        primary: '#6366f1',
        primaryOpacity: '#2E3350',
        onPrimary: '#FFFFFF',
        secondary: '#46b5e5',
        tertiary: '#1f2937',
        background: '#121212',
        onBackground: '#E5E7EB',
        surface: '#1E1E1E',
        surfaceSecondary: '#2C2C2C',
        text: '#FFFFFF',
        textSecondary: '#9CA3AF',
        outline: '#3F3F46',
        green: '#DFF6E0',
        onGreen: '#1D7B2E',
        blue: '#DBE9FE',
        onBlue: '#1D40B0',
        yellow: '#FEF9C3',
        onYellow: '#916025',
        orange: '#FEE7DB',
        onOrange: '#B0581D'
    }
}
